# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f99923b9fd09aab98490ad2868f209eb247d4b97ae9f5ceafe06ff4e8c7f150a8acc4cc1251d6d06237d8ec0ae17e8e80230f447f43d2368ee95715f5335fe23

test:
  secret_key_base: e04b4b3f2c8a0cad9c37a4a9b219b54a7c07a9a3b53ba0971938d09b9c4e4d3e4da2a0bfcdf8c70098c649745878c2a299627937f5d7fd1b909bea2234e1664d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
